### ISSUE TITLE
Parent class contrusctor can't use protected and private fields while being called in inherited classes

### ISSUE THREAD

**Issue by ChamberzSut** [TenebrisNoctua/ClassPP#1]
Here's the code:
```
library.Move = library.Action.extends "Move" {
	constructor = function(self: T.Move, data: {})
		if typeof(data) ~= "table" then error("data parameter for Move class-family should be a table, provided type: "..typeof(data)) end
		for object, value in data do
			if self.Data[object] then
				self.Data[object] = value
			else
				error(object.." is not valid data for Move. Check ReplicatedStorage.Framework.Action/library/Move/Protected/Data to get full list of availabe move data")
			end
		end
	end,
	Protected = {
		Data = {
			SFX = {},
			Animations = {},
		},
		OperateStart = function(self: T.Move, ...)
			-- override
		end,
		CancelStart = function(self: T.Move, ...)
			-- override
		end,
		OperateEnd = function(self: T.Move, ...)
			-- override
		end,
		CancelEnd = function(self: T.Move, ...)
			-- override
		end,
		ProceedPrepare = function(self: T.Move, ...)
			
		end,
		ProceedCancel = function(self: T.Move, ...)
			coroutine.wrap(self.CancelStart)(self, ...)
			coroutine.wrap(self.CancelEnd)(self, ...)
		end,
	}
}

library.CoreMove = library.Move.extends "CoreMove" {
}
```

When I create an object of the CoreMove class, it shows me this error:

```
{Class++}: Property "Data" is protected in this class.
--- Stack Trace ---
ReplicatedStorage.Framework.Action:86 function constructor
ReplicatedStorage.Framework.Class++:436
```

It disappears when i transfer Move class constructor to CoreMove class. It doesn't disappear when I remove inheritance of Move from Action as well.

U. P. D.: The issue was in edited version of API. Sorry, my bad

**Comment by TenebrisNoctua** [comment]
Great to hear that the issue resolved on its own, however, can I learn why you modified the API in the first place? Perhaps I can implement that modification as a feature if it's a good one.

**Comment by ChamberzSut** [comment]
Sure! I've made a timer class. Its realization involves calling loop function in the constructor, and it causes one issue: when i create a timer object anywhere, current thread of this _anywhere_ yields because of the loop. I haven't come up with using coroutines in the constructor just then, so i've looked on the API script to asynchronize constructor calls on lines 435 and 438.

This:
```
436    if superClassConstructor then superClassConstructor(newObj, ...) end
438    newObjTbl.Internal.constructor(newObj, ...)
```
Turned into this:
```
436    if superClassConstructor then coroutine.wrap(superClassConstructor)(newObj, ...) end
438    coroutine.wrap(newObjTbl.Internal.constructor)(newObj, ...)
```
     Why didn't i asynchronize the loop function inside of the timer class constructor instead? Well, firstly, as i said before, i haven't come up with using coroutines for calling loop function just then (i have no idea why), so i used ```task.spawn()```. It didn't work since you can't provide a function inside ```spawn()``` to any class as friendly because it doesn't have a name. Secondly, i needed to provide loop function as friendly so i could use private and protected fields inside of it (```coroutine.wrap``` is a perfect option for it, that's why i use it currently).
     Although, the issue is solved now and the solution is pretty simple (just use coroutine.wrap). Excuse me if there are some spelling mistakes (and i'm sure there are some) because i'm not a native speaker. Goodluck with future development!

**Comment by TenebrisNoctua** [comment]
I understand why you did it now, thank you. And as for the error, the super class constructor must be initialized first and the child class constructor must wait for the super one if it exists. With the coroutine however, it does not wait, therefore causing the bug you've mentioned. 

Aside from this, I'm glad you removed the modification as this would've caused other issues with other classes you would want to implement with inheritation, both functions running at the same time or one running late than the other would cause major issues. I advise you to not modify internals unless very necessary, and you're out of options. And even then, you should make a feature request so I can make the experience better!

**Comment by ChamberzSut** [comment]
I don't think you should add it as a new feature. You could just add a note in documentation that tells "asynchronize any yields in constructors by using `coroutine.wrap()`", so other people won't meet this issue
