### ISSUE TITLE
Friend functions can't access protected class fields

### ISSUE THREAD

**Issue by ChamberzSut** [TenebrisNoctua/ClassPP#2]
I've been using the module and have met a problem. Any friend functions for a certain class i use can't access protected fields. I've been looking through the original API and came to this part of code in __index metamethod.

```
if accessSpecifier ~= "Public" then
	if accessSpecifier == "Private" and not Util.inClassScope(class, false, true, Classes) then
		LogError("classPropertyIsPrivate", true, index)
	elseif accessSpecifier == "Internal" and Util.getMethodContext(7) ~= Type.typeof then
		LogError("classPropertyIsInternal", true, index)
	elseif accessSpecifier == "Protected" and not Util.inClassScope(class, true, false) then
		LogError("classPropertyIsProtected", true, index)
	end
end
```

The issue is that the lower part provided third argument (**includeFriend**) for `Util.inClassScope()` as **false** for some reason. Why so? Is this a typo? Why can't friend functions access the protected fields?

I marked this is as a bug since there is nothing said about it in documentation, so yeah

U. P. D.: The same issue is with the __newindex metamethod

**Comment by TenebrisNoctua** [comment]
Thanks for the issue post. Will be fixed in the next version. For now, you can update this line:
```luau
elseif accessSpecifier == "Protected" and not Util.inClassScope(class, true, false) then
```
to:
```luau
elseif accessSpecifier == "Protected" and not Util.inClassScope(class, true, true, Classes) then
```
To fix the problem for now.
